[2019-07-16 17:06:01] INFO [run: run.py, 11] ================================== ≤‚ ‘ø™ º ==================================
[2019-07-16 17:06:01] INFO [__init__: basecase.py, 34] url = https://tieba.baidu.com/present/getForumRank+ 
 + params = {'user_id': '256249580', 'forum_id': 24, 'pn': 0, 'ps': 4, 'type': 1} + 
 + method = GET
[2019-07-16 17:06:01] DEBUG [_new_conn: connectionpool.py, 813] Starting new HTTPS connection (1): tieba.baidu.com:443
[2019-07-16 17:06:05] DEBUG [_make_request: connectionpool.py, 393] https://tieba.baidu.com:443 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1 HTTP/1.1" 301 0
[2019-07-16 17:06:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): tieba.baidu.com:80
[2019-07-16 17:06:05] DEBUG [_make_request: connectionpool.py, 393] http://tieba.baidu.com:80 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1&red_tag=n0252747140 HTTP/1.1" 200 None
[2019-07-16 17:06:05] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/lottery/types+ 
 + params = {'key': '79ac25ba52d33f497a83d592ecb43de7'} + 
 + method = get
[2019-07-16 17:06:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:06:05] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /lottery/types?key=79ac25ba52d33f497a83d592ecb43de7 HTTP/1.1" 200 None
[2019-07-16 17:06:05] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/ip/ipNew+ 
 + params = {'ip': '192.168.1.145', 'key': 'a32b580d45e6a2a71ea32b8e199e94cb'} + 
 + method = get
[2019-07-16 17:06:05] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:06:05] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /ip/ipNew?ip=192.168.1.145&key=a32b580d45e6a2a71ea32b8e199e94cb HTTP/1.1" 200 None
[2019-07-16 17:06:05] INFO [__init__: basecase.py, 34] url = 192.168.1.16:9000/+ 
 + params = {'url': 'www.baidu.com', 'headers': 'headers', 'method': 'POST', 'data_type': 'APPLICATION/JSON', 'args': 'ars', 'expect_res': 'expect_res'} + 
 + method = post
[2019-07-16 17:06:05] INFO [run: run.py, 18] ================================== ≤‚ ‘Ω· ¯ ==================================
[2019-07-16 17:10:53] INFO [_check_file: autoreload.py, 202] F:\PycharmProjects\interface_framework\mock_tornado\config.py modified; restarting server
[2019-07-16 17:11:31] INFO [run: run.py, 11] ================================== ≤‚ ‘ø™ º ==================================
[2019-07-16 17:11:31] INFO [__init__: basecase.py, 34] url = https://tieba.baidu.com/present/getForumRank+ 
 + params = {'user_id': '256249580', 'forum_id': 24, 'pn': 0, 'ps': 4, 'type': 1} + 
 + method = GET
[2019-07-16 17:11:31] DEBUG [_new_conn: connectionpool.py, 813] Starting new HTTPS connection (1): tieba.baidu.com:443
[2019-07-16 17:11:33] DEBUG [_make_request: connectionpool.py, 393] https://tieba.baidu.com:443 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1 HTTP/1.1" 301 0
[2019-07-16 17:11:33] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): tieba.baidu.com:80
[2019-07-16 17:11:33] DEBUG [_make_request: connectionpool.py, 393] http://tieba.baidu.com:80 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1&red_tag=k0581245633 HTTP/1.1" 200 None
[2019-07-16 17:11:33] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/lottery/types+ 
 + params = {'key': '79ac25ba52d33f497a83d592ecb43de7'} + 
 + method = get
[2019-07-16 17:11:33] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:11:33] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /lottery/types?key=79ac25ba52d33f497a83d592ecb43de7 HTTP/1.1" 200 None
[2019-07-16 17:11:33] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/ip/ipNew+ 
 + params = {'ip': '192.168.1.145', 'key': 'a32b580d45e6a2a71ea32b8e199e94cb'} + 
 + method = get
[2019-07-16 17:11:33] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:11:33] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /ip/ipNew?ip=192.168.1.145&key=a32b580d45e6a2a71ea32b8e199e94cb HTTP/1.1" 200 None
[2019-07-16 17:11:33] INFO [__init__: basecase.py, 34] url = 192.168.1.16:9000/+ 
 + params = {'url': 'www.baidu.com', 'headers': 'headers', 'method': 'POST', 'data_type': 'APPLICATION/JSON', 'args': 'ars', 'expect_res': 'expect_res'} + 
 + method = post
[2019-07-16 17:11:33] INFO [run: run.py, 18] ================================== ≤‚ ‘Ω· ¯ ==================================
[2019-07-16 17:12:16] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:12:51] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:17:18] INFO [log_request: web.py, 2246] 200 GET / (192.168.1.16) 2.00ms
[2019-07-16 17:18:17] ERROR [log_exception: web.py, 1788] Uncaught exception GET / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:18:17] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:18:17] ERROR [log_request: web.py, 2246] 500 GET / (192.168.1.16) 5.00ms
[2019-07-16 17:19:46] INFO [log_request: web.py, 2246] 200 GET / (192.168.1.16) 1.00ms
[2019-07-16 17:20:06] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:20:22] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:20:22] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:20:22] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 3.00ms
[2019-07-16 17:21:03] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:21:03] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:21:03] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:21:13] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:21:13] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:21:13] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:21:27] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:21:27] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:21:27] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 23.00ms
[2019-07-16 17:21:44] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:21:44] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:21:44] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:22:15] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:22:22] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:24:41] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:25:01] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:25:11] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:25:45] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 0.00ms
[2019-07-16 17:25:49] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:28:21] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:29:49] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:29:49] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:29:49] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 3.00ms
[2019-07-16 17:29:58] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:29:58] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:29:58] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 3.00ms
[2019-07-16 17:30:16] ERROR [log_exception: web.py, 1788] Uncaught exception POST / (192.168.1.16)
HTTPServerRequest(protocol='http', host='192.168.1.16:9000', method='POST', uri='/', version='HTTP/1.1', remote_ip='192.168.1.16')
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2019-07-16 17:30:16] ERROR [send_error: web.py, 1216] Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1676, in _execute
    result = self.prepare()
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 10, in prepare
    if self.request.headers.get("Content-Type").startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\tornado\web.py", line 1214, in send_error
    self.write_error(status_code, **kwargs)
  File "F:\PycharmProjects\interface_framework\mock_tornado\handlers\IndexHandler.py", line 43, in write_error
    self.write(u"<p>¥ÌŒÛ√˚£∫%s</p>" % kwargs["title"])
KeyError: 'title'
[2019-07-16 17:30:16] ERROR [log_request: web.py, 2246] 500 POST / (192.168.1.16) 5.00ms
[2019-07-16 17:32:03] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:32:11] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:32:29] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:32:52] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:38:36] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:38:45] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 0.00ms
[2019-07-16 17:39:04] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 1.00ms
[2019-07-16 17:40:18] INFO [run: run.py, 11] ================================== ≤‚ ‘ø™ º ==================================
[2019-07-16 17:40:18] INFO [__init__: basecase.py, 34] url = https://tieba.baidu.com/present/getForumRank+ 
 + params = {'user_id': '256249580', 'forum_id': 24, 'pn': 0, 'ps': 4, 'type': 1} + 
 + method = GET
[2019-07-16 17:40:18] DEBUG [_new_conn: connectionpool.py, 813] Starting new HTTPS connection (1): tieba.baidu.com:443
[2019-07-16 17:40:18] DEBUG [_make_request: connectionpool.py, 393] https://tieba.baidu.com:443 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1 HTTP/1.1" 301 0
[2019-07-16 17:40:18] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): tieba.baidu.com:80
[2019-07-16 17:40:18] DEBUG [_make_request: connectionpool.py, 393] http://tieba.baidu.com:80 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1&red_tag=z2306230292 HTTP/1.1" 200 None
[2019-07-16 17:40:18] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/lottery/types+ 
 + params = {'key': '79ac25ba52d33f497a83d592ecb43de7'} + 
 + method = get
[2019-07-16 17:40:18] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:40:18] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /lottery/types?key=79ac25ba52d33f497a83d592ecb43de7 HTTP/1.1" 200 None
[2019-07-16 17:40:18] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/ip/ipNew+ 
 + params = {'ip': '192.168.1.145', 'key': 'a32b580d45e6a2a71ea32b8e199e94cb'} + 
 + method = get
[2019-07-16 17:40:18] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:40:18] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /ip/ipNew?ip=192.168.1.145&key=a32b580d45e6a2a71ea32b8e199e94cb HTTP/1.1" 200 None
[2019-07-16 17:40:18] INFO [__init__: basecase.py, 34] url = http://192.168.1.16:9000/+ 
 + params = {'url': 'www.baidu.com', 'headers': 'headers', 'method': 'POST', 'data_type': 'APPLICATION/JSON', 'args': 'ars', 'expect_res': 'expect_res'} + 
 + method = post
[2019-07-16 17:40:18] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 192.168.1.16:9000
[2019-07-16 17:40:18] INFO [log_request: web.py, 2246] 200 POST / (192.168.1.16) 2.00ms
[2019-07-16 17:40:18] DEBUG [_make_request: connectionpool.py, 393] http://192.168.1.16:9000 "POST / HTTP/1.1" 200 140
[2019-07-16 17:40:18] INFO [run: run.py, 18] ================================== ≤‚ ‘Ω· ¯ ==================================
[2019-07-16 17:42:35] INFO [run: run.py, 11] ================================== ≤‚ ‘ø™ º ==================================
[2019-07-16 17:56:01] INFO [run: run.py, 11] ================================== ≤‚ ‘ø™ º ==================================
[2019-07-16 17:56:01] INFO [__init__: basecase.py, 34] url = https://tieba.baidu.com/present/getForumRank+ 
 + params = {'user_id': '256249580', 'forum_id': 24, 'pn': 0, 'ps': 4, 'type': 1} + 
 + method = GET
[2019-07-16 17:56:01] DEBUG [_new_conn: connectionpool.py, 813] Starting new HTTPS connection (1): tieba.baidu.com:443
[2019-07-16 17:56:01] DEBUG [_make_request: connectionpool.py, 393] https://tieba.baidu.com:443 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1 HTTP/1.1" 301 0
[2019-07-16 17:56:01] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): tieba.baidu.com:80
[2019-07-16 17:56:01] DEBUG [_make_request: connectionpool.py, 393] http://tieba.baidu.com:80 "GET /present/getForumRank?user_id=256249580&forum_id=24&pn=0&ps=4&type=1&red_tag=p3248838692 HTTP/1.1" 200 None
[2019-07-16 17:56:01] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/lottery/types+ 
 + params = {'key': '79ac25ba52d33f497a83d592ecb43de7'} + 
 + method = get
[2019-07-16 17:56:01] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:56:01] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /lottery/types?key=79ac25ba52d33f497a83d592ecb43de7 HTTP/1.1" 200 None
[2019-07-16 17:56:01] INFO [__init__: basecase.py, 34] url = http://apis.juhe.cn/ip/ipNew+ 
 + params = {'ip': '192.168.1.145', 'key': 'a32b580d45e6a2a71ea32b8e199e94cb'} + 
 + method = get
[2019-07-16 17:56:01] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): apis.juhe.cn:80
[2019-07-16 17:56:01] DEBUG [_make_request: connectionpool.py, 393] http://apis.juhe.cn:80 "GET /ip/ipNew?ip=192.168.1.145&key=a32b580d45e6a2a71ea32b8e199e94cb HTTP/1.1" 200 None
[2019-07-16 17:56:01] INFO [__init__: basecase.py, 34] url = http://192.168.1.16:9000/+ 
 + params = {'url': 'www.baidu.com', 'headers': 'headers', 'method': 'POST', 'data_type': 'APPLICATION/JSON', 'args': 'ars', 'expect_res': 'expect_res'} + 
 + method = post
[2019-07-16 17:56:01] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 192.168.1.16:9000
[2019-07-16 17:56:02] INFO [run: run.py, 18] ================================== ≤‚ ‘Ω· ¯ ==================================
[2019-07-16 17:56:18] INFO [log_request: web.py, 2246] 304 GET /python (192.168.1.16) 1.00ms
